server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  messages:
    basename: i18n/messages
    cache-duration: 3600ms
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    converters:
      preferred-json-mapper: jackson
  datasource:
    url: jdbc:mysql://localhost:3306/vertical?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: d9d2j9w2
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-active: 5
      max-idle: 2
      min-idle: 1
      initial-size: 1
      initialize: false
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-wait-millis: 30000
      validation-query: select 1
      time-between-eviction-runs-millis: 20000
      min-evictable-idle-time-millis: 28700
  resources:
    add-mappings: true
  jackson:
    format:
      format-long-class: true
pagehelper:
  helper-dialect: mysql
version: 1.0
localhost-href: voally.com
logging:
  level:
    com:
      voally:
        vertical:
          mapper: debug
env: dev